const { Router } = require("express");
const walletController = require("../controllers/walletController");
const tokenController = require("../controllers/tokenController");
const collectionController = require("../controllers/collectionController");
const router = new Router();
const bodyParser = require("body-parser");
const jsonParser = bodyParser.json();
router.post("/createWallet", jsonParser, walletController.createWallet);
router.get("/wallet/:walletAddress", walletController.getAWallet);
router.post("/authentication", jsonParser, walletController.authentication);
router.get("/tokens", tokenController.getTokens);
router.post("/:walletAddress/createToken", jsonParser, tokenController.createToken);
router.get("/tokens/:tokenId", tokenController.getAToken);
router.get("/:collectionOwner/collections/:collectionName", collectionController.getACollection);
router.get("/:creatorName/tokens", tokenController.getTokensByCreator);
router.get("/:ownerName/collectibles", tokenController.getTokensByOwner);
router.get("/:ownerName/collections", collectionController.getCollectionsByOwner);
router.get("/collections/trending", collectionController.getTrendingCollections);
router.get("/collections/topCollections", collectionController.getTopCollections);
router.get("/wallets", walletController.getWallets);
module.exports = router;
