const { Router } = require("express");
const walletController = require("../controllers/walletController");
const tokenController = require("../controllers/tokenController");
const router = new Router();
const bodyParser = require("body-parser");
const jsonParser = bodyParser.json();
router.post("/createWallet", jsonParser, walletController.createWallet);
router.post("/authentication", jsonParser, walletController.authentication);
router.get("/marketplace", tokenController.getTokens);
router.post("/:walletAddress/createToken", jsonParser, tokenController.createToken);
router.get("/token/:tokenId", tokenController.getAToken);
module.exports = router;
